name: Test DevOps
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: http://178.18.254.89/
          username: root
          password: hD5H9Mf5kwci
          script: whoami
