name: Test DevOps
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 178.18.254.89
          username: root
          password: hD5H9Mf5kwci
          token: ${{ secrets.myToken }}
          script: |
            . ~/.nvm/nvm.sh
            whoami
            pwd
            ls
            cd /var/www/my-devops
            git pull
            pm2 restart index.js
